name: totp-based-2fa-server

services:
  postgres:
    container_name: totp-based-2fa-server-postgres
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
  