env_files = [".env"]

[tasks.enter-psql]
category = "postgres"
description = "Enter psql container"
script = [
    '''
    echo "Entering psql container..."
    docker exec -it rust-axum-ddd-example-postgres psql -U ${POSTGRES_APP_USER} -d ${POSTGRES_DB}
    '''
]

[tasks.create-migration]
category = "sqlx"
description = "Create a new migration"
script = [
    '''
    echo "Creating a new migration..."
    sqlx migrate add -r {{ARGS}}
    '''
]

[tasks.db-migrate]
category = "sqlx"
description = "Run migrations"
script = [
    '''
    echo "Running migrations..."
    sqlx migrate run --database-url ${DATABASE_URL}
    '''
]

[tasks.db-rollback]
category = "sqlx"
description = "Rollback migrations"
script = [
    '''
    echo "Rolling back migrations..."
    sqlx migrate revert --database-url ${DATABASE_URL}
    '''
]
