CREATE TABLE IF NOT EXISTS user (
    id SERIAL,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_id_pk PRIMARY KEY (id)
);
