#!/bin/sh -eu

psql -v ON_ERROR_STOP=1 -U "${POSTGRES_USER}" <<- _EOT_
    BEGIN;
        CREATE USER ${POSTGRES_APP_USER} WITH PASSWORD '${POSTGRES_APP_PASSWORD}';
        ALTER ROLE ${POSTGRES_DB} WITH CREATEDB CREATEROLE LOGIN;
        ALTER DATABASE ${POSTGRES_APP_USER} OWNER TO ${POSTGRES_APP_USER};
    COMMIT;
_EOT_
